-- Migration to add incomes table for funds injection (Kassa Daxili)
CREATE TABLE IF NOT EXISTS public.incomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    description TEXT,
    date TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id BIGINT REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;

-- Add RLS Policies
CREATE POLICY "Users can view incomes" ON public.incomes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert incomes" ON public.incomes FOR INSERT TO authenticated WITH CHECK (true);

-- Grant permissions
GRANT ALL ON public.incomes TO authenticated;
GRANT ALL ON public.incomes TO anon;
GRANT ALL ON public.incomes TO service_role;
